# Generated by Django 4.2.1 on 2023-05-09 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='password1',
        ),
    ]
